(define-constant err-unauthorized (err u101))
(define-constant err-invalid-role (err u102))
(define-constant err-dept-not-found (err u103))
(define-data-var dept-counter uint u0)
(define-data-var role-counter uint u0)
(define-map departments { dept-id: uint } { admin: principal, dept-name: (string-ascii 50), budget-allocation: uint, employee-count: uint, status: (string-ascii 15) })
(define-map org-roles { role-id: uint } { dept-id: uint, role-name: (string-ascii 40), classification: (string-ascii 25), salary-band: uint, filled-positions: uint })
(define-map reporting-structure { role-id: uint, subordinate-role-id: uint } { hierarchy-level: uint })
(define-map performance-metrics { dept-id: uint, metric-id: uint } { kpi-type: (string-ascii 30), target-value: uint, current-value: uint, measurement-date: uint })
(define-map compliance-records { dept-id: uint, record-id: uint } { audit-type: (string-ascii 30), compliance-status: (string-ascii 20), audit-date: uint, findings: uint })
(define-public (create-department (dept-name (string-ascii 50)) (budget uint)) (let ((dept-id (var-get dept-counter))) (map-set departments { dept-id: dept-id } { admin: tx-sender, dept-name: dept-name, budget-allocation: budget, employee-count: u0, status: "active" }) (var-set dept-counter (+ dept-id u1)) (ok dept-id)))
(define-public (define-role (dept-id uint) (role-name (string-ascii 40)) (classification (string-ascii 25)) (salary-band uint)) (let ((dept (map-get? departments { dept-id: dept-id })) (role-id (var-get role-counter))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set org-roles { role-id: role-id } { dept-id: dept-id, role-name: role-name, classification: classification, salary-band: salary-band, filled-positions: u0 }) (var-set role-counter (+ role-id u1)) (ok role-id)))
(define-public (establish-hierarchy (parent-role-id uint) (child-role-id uint) (level uint)) (map-set reporting-structure { role-id: parent-role-id, subordinate-role-id: child-role-id } { hierarchy-level: level }) (ok true))
(define-public (record-performance (dept-id uint) (metric-id uint) (kpi-type (string-ascii 30)) (target uint) (current uint)) (let ((dept (map-get? departments { dept-id: dept-id }))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set performance-metrics { dept-id: dept-id, metric-id: metric-id } { kpi-type: kpi-type, target-value: target, current-value: current, measurement-date: burn-block-height }) (ok true)))
(define-public (log-compliance-audit (dept-id uint) (record-id uint) (audit-type (string-ascii 30)) (status (string-ascii 20)) (findings uint)) (let ((dept (map-get? departments { dept-id: dept-id }))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set compliance-records { dept-id: dept-id, record-id: record-id } { audit-type: audit-type, compliance-status: status, audit-date: burn-block-height, findings: findings }) (ok true)))
(define-read-only (get-department (dept-id uint)) (map-get? departments { dept-id: dept-id }))
(define-read-only (get-role (role-id uint)) (map-get? org-roles { role-id: role-id }))
(define-read-only (get-hierarchy (parent-role-id uint) (child-role-id uint)) (map-get? reporting-structure { role-id: parent-role-id, subordinate-role-id: child-role-id }))
