(define-constant err-unauthorized (err u101))
(define-constant err-dept-not-found (err u103))
(define-data-var dept-counter uint u0)
(define-map departments { dept-id: uint } { admin: principal, dept-name: (string-ascii 50) })
(define-map org-roles { role-id: uint, dept-id: uint } { role-name: (string-ascii 40), salary-band: uint })
(define-map performance-kpis { dept-id: uint, kpi-id: uint } { kpi-name: (string-ascii 30), target: uint })
(define-map audit-logs { dept-id: uint, log-id: uint } { audit-type: (string-ascii 25), findings: uint })
(define-public (create-department (dept-name (string-ascii 50))) (let ((dept-id (var-get dept-counter))) (map-set departments { dept-id: dept-id } { admin: tx-sender, dept-name: dept-name }) (var-set dept-counter (+ dept-id u1)) (ok dept-id)))
(define-public (add-role (role-id uint) (dept-id uint) (role-name (string-ascii 40)) (salary uint)) (let ((dept (map-get? departments { dept-id: dept-id }))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set org-roles { role-id: role-id, dept-id: dept-id } { role-name: role-name, salary-band: salary }) (ok true)))
(define-public (record-kpi (dept-id uint) (kpi-id uint) (kpi-name (string-ascii 30)) (target uint)) (let ((dept (map-get? departments { dept-id: dept-id }))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set performance-kpis { dept-id: dept-id, kpi-id: kpi-id } { kpi-name: kpi-name, target: target }) (ok true)))
(define-public (log-audit (dept-id uint) (log-id uint) (audit-type (string-ascii 25)) (findings uint)) (let ((dept (map-get? departments { dept-id: dept-id }))) (asserts! (is-some dept) err-dept-not-found) (asserts! (is-eq tx-sender (get admin (unwrap-panic dept))) err-unauthorized) (map-set audit-logs { dept-id: dept-id, log-id: log-id } { audit-type: audit-type, findings: findings }) (ok true)))
(define-read-only (get-department (dept-id uint)) (map-get? departments { dept-id: dept-id }))
(define-read-only (get-role (role-id uint) (dept-id uint)) (map-get? org-roles { role-id: role-id, dept-id: dept-id }))
